name: GoTest

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: go get github.com/golang/mock/gomock 
      uses: actions/checkout@v2
      
    - name: Get dependencies
      run: cd server && go get -v -t -d ./...
      
    - name: Test
      run: go test -v ./server/test
